### ISSUE TITLE
Special Character "&" issue still persistes

### ISSUE THREAD

**Issue by geet96** [CAAPIM/iOS-MAS-Foundation#133]
Hi, I had opened an issue related to the truncation of password or username if the special character '&' is passed in password through your SDK, the link is as below
https://github.com/CAAPIM/iOS-MAS-Foundation/issues/126

I understand you made a fix by using the native iOS encoding using stringByAddingPercentEncodingWithAllowedCharacters for character set "!*'();:@&=+$,/?%#[] \" in your function
escapeValueForURLParameter however this has not helped resolve the issue and I believe the issue is at another place as I have been going through your code and I realized the method 

[[MASNetworkingService sharedService] postTo:registerEndpoint
                                  withParameters:parameterInfo
                                      andHeaders:headerInfo
                                     requestType:MASRequestResponseTypeTextPlain
                                    responseType:MASRequestResponseTypeTextPlain
                                      completion:^(NSDictionary<NSString *,id> * _Nullable responseInfo, NSError * _Nullable error) {}];
Throws an error of 401 unauthorized, when trying to call data

- (void)registerDeviceWithCredential:(MASCompletionErrorBlock)completion

and hence never reaches the method escapeValueForURLParameter where you have made the fix for the previous opened issue, can you please Help us out as to why it returns unautorized at this point.

**Comment by jhoongo** [comment]
Hi,

Thanks for getting back to us, and providing the information.

Typically, if Mobile SDK receives HTTP status code 401, as you would probably know, this basically means invalid credentials, or unauthorized.
This could be caused due to two issues:

1. Credentials are correct and correct credentials are provided to Mobile SDK; however, Mobile SDK fails to parse or transmit the data inappropriately to the server which will result in unauthorized.
2. Credentials are incorrect, or LDAP is misconfigured on the server side.

I've checked on the first scenario, and was able to confirm with username and/or password containing special characters are being transmitted without any alternation, and are successfully validated on the server side.

So, my assumption is that there could be some problems on LDAP configuration, or invalid user credentials.

If you are the customer of CA Technologies and purchased MAG product, we can deal with this matter in more official way of handling the issue which is through CA Support.  This is an effort to investigate with more professional on server and product configuration aspect.

If you can provide bit more details on your situation, that would also be helpful.

Please note that this is a public GitHub repository, please do not share any sensitive information on the contract, credentials, and/or environment.

Thanks,

**Comment by jhoongo** [comment]
Hi,

Just to follow up on the issue here.
I understand that you've already went through the official CA Support channel, but just to double check with you directly on one thing.

Are you currently using the Stable branch for the development?
I am not quite sure that you have an access to the system, or if the support provided you the details that I've provided, it looks like that the URL query parameters are correctly encoding the values with special characters.

If you are using the Stable version of SDK, if you could please verify whether you include the entire project as a dependency of your project, or binary, that would be helpful.

Thanks,

**Comment by geet96** [comment]
I take the latest code from the stable branch and use it to create the binary of MASFoundation.framework and include that  in my project

**Comment by jhoongo** [comment]
Hi,

I've tested it on the latest Stable branch, and was able to verify that the URL query parameters are being properly encoded.  Is it just & sign that isn't being properly encoded or other special characters that weren't encoded are still not?  If other special characters are now being encoded and it's just the & sign, then we can look further.

I am pretty sure that you've already did, but if you can double check on the link of the binary are pointed to the correct framework, and clean up the project, that might be helpful.

If this still doesn't solve the problem, I will communicate within the team to figure out other ways that I can help you with.

<img width="1267" alt="log" src="https://user-images.githubusercontent.com/2975675/36498270-a7b9a3a8-16f2-11e8-934f-761c9a1c2cb1.png">

**Comment by geet96** [comment]
Hi,

  I tested with the "+" sign too, and that is also not accepted by the SDK and throws an error, surprisingly I noticed that the error thrown is from the register device call, which is your MAG SDK call and your patch for URL query parameters does not come into picture.

**Comment by jhoongo** [comment]
Hi,

Can you give it a try with the binary that we posted on Releases page?
https://github.com/CAAPIM/iOS-MAS-Foundation/releases

Please use the one that is marked as pre-release, Stable-Version-1.6.01-Build-8.
This is the binary that we've tested, and came from Stable branch.

Please let me know if you still experience the issue with the binary.

Thanks,

**Comment by jhoongo** [comment]
Hi,

If you still experience the problem after trying pre-release binary, please send me an email to **** then we will try to sort this thing out with you directly.
Let me know what is your timezone, just in case if we need to schedule a meeting with you to walk through the problem.

Thanks,
